/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;



import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import modelo.PeriodoReporte;

/**
 *
 * @author javisarango
 */
public class Frm_ReportedeVentas extends javax.swing.JDialog {
    fondoPaneles paneles = new fondoPaneles();
    
    /**
     * Creates new form Frm_ReportedeVentas
     */
    public Frm_ReportedeVentas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);     
                 
        initComponents();
      cargarcbxTipoReporte();
        
    }
    
    public void cargarcbxTipoReporte(){
    cbxTipoReporte.removeAllItems();
        for (int i = 0; i < PeriodoReporte.values().length; i++) {
            cbxTipoReporte.addItem(PeriodoReporte.values()[i].toString());
        }
    cbxTipoReporte.updateUI();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGeneral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxTipoReporte = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        PanelGrafico = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        PanelGeneral.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelGeneral.setLayout(null);

        jLabel1.setFont(new java.awt.Font("MathJax_Math", 1, 18)); // NOI18N
        jLabel1.setText("Reporte de Ventas del Negocio");
        PanelGeneral.add(jLabel1);
        jLabel1.setBounds(210, 10, 250, 30);

        jLabel2.setText("Tipo de Reporte:");
        PanelGeneral.add(jLabel2);
        jLabel2.setBounds(30, 50, 110, 30);

        cbxTipoReporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        PanelGeneral.add(cbxTipoReporte);
        cbxTipoReporte.setBounds(150, 50, 120, 30);

        jButton1.setText("Generar Reporte");
        PanelGeneral.add(jButton1);
        jButton1.setBounds(360, 50, 140, 30);

        PanelGrafico.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelGeneral.add(PanelGrafico);
        PanelGrafico.setBounds(10, 120, 500, 230);

        getContentPane().add(PanelGeneral);
        PanelGeneral.setBounds(0, 0, 560, 360);

        setSize(new java.awt.Dimension(568, 393));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_ReportedeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_ReportedeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_ReportedeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_ReportedeVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Frm_ReportedeVentas dialog = new Frm_ReportedeVentas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelGeneral;
    private javax.swing.JPanel PanelGrafico;
    private javax.swing.JComboBox<String> cbxTipoReporte;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
 /*
        Agrega una imagen al JPanel
     */
    class fondoPaneles extends JPanel {

        private Image fondo;

        @Override
        public void paint(Graphics g) {
            fondo = new ImageIcon(getClass().getResource("src/RecursosMultimedia/reporte-de-ventas.jpg")).getImage();
            g.drawImage(fondo, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }

    }

}
