/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import java.sql.Connection;
import controlador.Conexion;
import controlador.dao.ClienteContro;
import controlador.dao.ProductoDao;
import controlador.dao.VentaDao;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import modelo.Cliente;

/**
 *
 * @author JavierSarango
 */
public class Frm_Ventas extends javax.swing.JDialog {

    fondoLabel logotipo = new fondoLabel();
    fondoPieLabel pie = new fondoPieLabel();
    private VentaDao vd = new VentaDao();
    private ProductoDao pd = new ProductoDao();
//    private ClienteContro cc = new ClienteContro();

//    private Connection cn = Conexion.getConecction();
   
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    /**
     * Creates new form Frm_Ventas
     */
    public Frm_Ventas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        super.setTitle("Ventas");
        jTable_productos.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        jTable_productos.getTableHeader().setOpaque(false);
        jTable_productos.getTableHeader().setBackground(new Color(153,153,255));
        jTable_productos.getTableHeader().setForeground(new Color(0,0,0));
        jTable_productos.setRowHeight(25);
//        CargarProductos();
//        CargarComboClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_cliente_buscar = new javax.swing.JTextField();
        jButton_busca_cliente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_productos = new javax.swing.JTable();
        jlabelPie = new fondoPieLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_subtotal = new javax.swing.JTextField();
        txt_descuento = new javax.swing.JTextField();
        txt_iva = new javax.swing.JTextField();
        txt_total_pagar = new javax.swing.JTextField();
        txt_efectivo = new javax.swing.JTextField();
        txt_cambio = new javax.swing.JTextField();
        jButton_calcular_cambio = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtResultadoCliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCodProducto = new javax.swing.JTextField();
        jButton_busca_producto = new javax.swing.JButton();
        jSpinner_Cantidad = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        txtCodProducto1 = new javax.swing.JTextField();
        jButton_busca_cliente2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtResultadoCliente1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtResultadoCliente2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabelSerie = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        JLabelLogo = new fondoLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Cliente");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(370, 180, 50, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Precio Producto:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 280, 110, 30);

        txt_cliente_buscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txt_cliente_buscar);
        txt_cliente_buscar.setBounds(130, 180, 120, 30);

        jButton_busca_cliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_busca_cliente.setText("Buscar");
        jButton_busca_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_busca_clienteActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_busca_cliente);
        jButton_busca_cliente.setBounds(260, 180, 90, 30);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(null);

        jTable_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NRO", "idVenta", "fecha", "Title 4"
            }
        ));
        jTable_productos.setFocusable(false);
        jTable_productos.setRowHeight(25);
        jTable_productos.setSelectionBackground(new java.awt.Color(153, 153, 255));
        jTable_productos.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable_productos.setShowHorizontalLines(true);
        jTable_productos.getTableHeader().setReorderingAllowed(false);
        jTable_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_productosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_productos);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 410, 200);
        jPanel3.add(jlabelPie);
        jlabelPie.setBounds(-10, 170, 720, 100);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 370, 430, 220);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Subtotal:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 20, 58, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Descuento:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 50, 69, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Iva:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 80, 23, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Total a pagar:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 110, 85, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Efectivo:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 150, 53, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Cambio:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 180, 49, 15);

        txt_subtotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txt_subtotal);
        txt_subtotal.setBounds(100, 20, 120, 23);

        txt_descuento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txt_descuento);
        txt_descuento.setBounds(100, 50, 120, 23);

        txt_iva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txt_iva);
        txt_iva.setBounds(100, 80, 120, 23);

        txt_total_pagar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_total_pagar.setEnabled(false);
        jPanel2.add(txt_total_pagar);
        txt_total_pagar.setBounds(100, 110, 120, 23);

        txt_efectivo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(txt_efectivo);
        txt_efectivo.setBounds(100, 150, 120, 23);

        txt_cambio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_cambio.setEnabled(false);
        jPanel2.add(txt_cambio);
        txt_cambio.setBounds(100, 180, 120, 23);

        jButton_calcular_cambio.setBackground(new java.awt.Color(51, 255, 255));
        jButton_calcular_cambio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_calcular_cambio.setText("Calcular Cambio");
        jButton_calcular_cambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_calcular_cambioActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_calcular_cambio);
        jButton_calcular_cambio.setBounds(90, 220, 130, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(460, 330, 230, 270);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Cod. Producto");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 230, 100, 30);
        jPanel1.add(txtResultadoCliente);
        txtResultadoCliente.setBounds(470, 180, 220, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Fecha:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(370, 140, 60, 30);
        jPanel1.add(txtCodProducto);
        txtCodProducto.setBounds(130, 230, 120, 30);

        jButton_busca_producto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_busca_producto.setText("Buscar");
        jButton_busca_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_busca_productoActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_busca_producto);
        jButton_busca_producto.setBounds(260, 230, 90, 30);
        jPanel1.add(jSpinner_Cantidad);
        jSpinner_Cantidad.setBounds(130, 330, 120, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Cantidad:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(20, 330, 80, 30);
        jPanel1.add(txtCodProducto1);
        txtCodProducto1.setBounds(130, 280, 120, 30);

        jButton_busca_cliente2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_busca_cliente2.setText("Agregar");
        jButton_busca_cliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_busca_cliente2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_busca_cliente2);
        jButton_busca_cliente2.setBounds(260, 280, 90, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Descripción:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(370, 230, 80, 30);
        jPanel1.add(txtResultadoCliente1);
        txtResultadoCliente1.setBounds(470, 230, 220, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Stock:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(370, 280, 70, 30);
        jPanel1.add(txtResultadoCliente2);
        txtResultadoCliente2.setBounds(470, 280, 220, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("CI. Cliente");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(20, 180, 80, 30);
        jPanel1.add(jLabelSerie);
        jLabelSerie.setBounds(130, 140, 120, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Nro:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(20, 140, 60, 30);
        jPanel1.add(jLabelFecha);
        jLabelFecha.setBounds(470, 140, 220, 30);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setOpaque(false);
        jPanel4.setLayout(null);
        jPanel4.add(JLabelLogo);
        JLabelLogo.setBounds(10, 10, 260, 90);

        jLabel15.setText("VENTA DE ARTICULOS TECNOLÓGICOS");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(370, 60, 230, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PUNTO DE VENTA OMICRON");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(350, 30, 270, 22);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(40, 10, 640, 120);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 720, 640);

        setSize(new java.awt.Dimension(732, 651));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_busca_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_busca_clienteActionPerformed
        buscarCliente();
    }//GEN-LAST:event_jButton_busca_clienteActionPerformed

    private void buscarCliente() {
        String idCliente = txt_cliente_buscar.getText();
        Integer respuesta;
        if (txt_cliente_buscar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe Ingresar el id de Cliente");
        } else {

//            if (vd.buscarCliente(Integer.parseInt(idCliente))!= null) {
//                System.out.println("Esto hay en :"+vd.buscarCliente(Integer.parseInt(idCliente)));
////                txtResultadoCliente.setText(cc.getCliente().getRazonSocial());
//                txtCodProducto1.setRequestFocusEnabled(true);
//            }
            respuesta = JOptionPane.showConfirmDialog(this, "El cliente no esta Registrado, ¿Desea Hacerlo?");
            if (respuesta == 0) {
                FrmCliente ventanaCliente = new FrmCliente();
                ventanaCliente.setVisible(true);
                this.dispose();
                
            }

        }

    }
    
 public Cliente listarIDCliente (Integer dni){
    String sql = "Select * from persona where id_Persona = '?'";
    Cliente cliente = new Cliente();
        try {
            con = Conexion.getConecction();
            ps = con.prepareStatement(sql);
            ps.setInt(1, dni);
            rs = ps.executeQuery();
            while (rs.next()) {                
                cliente.setId_cliente(rs.getInt(1));
                cliente.setRazonSocial(rs.getString(2));
                cliente.setTelefono(rs.getString(3));
                cliente.setCelular(rs.getString(4));
                cliente.setCorreo(rs.getString(5));
                cliente.setDireccion(rs.getString(6));
                cliente.setIdentificacion(rs.getString(7));
            }
        } catch (Exception e) {
            System.out.println("Error en listar Id cliente");
            e.printStackTrace();
        }
    return cliente;
    
    }
//    private void CargarProductos() {
//
//        String sql = "select * from producto";
//        java.sql.Statement st;
//        try {
////            st = cn.createStatement();
////            ResultSet rs = st.executeQuery(sql);
////            jComboBox_producto.removeAllItems();
////            jComboBox_producto.addItem("Seleccione producto:");
//            while (rs.next()) {
////                jComboBox_producto.addItem(rs.getString("descripcion"));
//            }
////            CargarComboClientes();
////            cn.close();
//        } catch (SQLException e) {
//            System.out.println("¡Error al cargar productos, !" + e);
//        }
//    }

//    private void CargarComboClientes() {
//
//        String sql = "select * from persona";
//        java.sql.Statement st;
//        try {
////            st = cn.createStatement();
////            ResultSet rs = st.executeQuery(sql);
////            jComboBox_cliente.removeAllItems();
////            jComboBox_cliente.addItem("Seleccione cliente:");
//            while (rs.next()) {
//                System.out.println(rs.getString("razonSocial"));
////                jComboBox_cliente.addItem(rs.getString("razonSocial"));
//            }
////            cn.close();
//        } catch (SQLException e) {
//            System.out.println("¡Error al cargar clientes, !" + e);
//        }
//    }

    private void jTable_productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_productosMouseClicked


    }//GEN-LAST:event_jTable_productosMouseClicked
//    public Integer stock(String producto) {
//        Integer cantidadProductosBD = 0;
//        try {
//
//            String sql = "select unidades from producto where descripcion = '" + producto + "'";
//            java.sql.Statement st;
////            st = cn.createStatement();
////            ResultSet rs = st.executeQuery(sql);
//            while (rs.next()) {
//                cantidadProductosBD = rs.getInt("unidades");
//            }
////            cn.close();
//            return cantidadProductosBD;
//        } catch (SQLException e) {
//            System.out.println("Error al restar cantidad 1, " + e);
//            return null;
//        }
//
//    }
    private void jButton_calcular_cambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_calcular_cambioActionPerformed
        if (!txt_efectivo.getText().isEmpty()) {
            //validamos que el usuario no ingrese otros caracteres no numericos 
            boolean validacion = vd.validarDouble(txt_efectivo.getText());
            if (validacion == true) {
                //validar que el efectivo sea mayor a cero
                Double efc = Double.parseDouble(txt_efectivo.getText().trim());
                Double top = Double.parseDouble(txt_total_pagar.getText().trim());

                if (efc < top) {
                    JOptionPane.showMessageDialog(null, "El Dinero en efectivo no es suficiente");
                } else {
                    double cambio = (efc - top);
                    double cambi = (double) Math.round(cambio * 100d) / 100;
                    String camb = String.valueOf(cambi);
                    txt_cambio.setText(camb);
                }
            } else {
                JOptionPane.showMessageDialog(null, "No de admiten caracteres no numericos");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese dinero en efectivo para calcular cambio");
        }

    }//GEN-LAST:event_jButton_calcular_cambioActionPerformed

    private void jButton_busca_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_busca_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_busca_productoActionPerformed

    private void jButton_busca_cliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_busca_cliente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_busca_cliente2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Frm_Ventas dialog = new Frm_Ventas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    /*
    Agrega una imagen al JLabel
     */
    class fondoLabel extends JLabel {

        private Image logo;

        @Override
        public void paint(Graphics g) {
            logo = new ImageIcon(getClass().getResource("/RecursosMultimedia/OmicronLogo.jpg")).getImage();
            g.drawImage(logo, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }

    }
       class fondoPieLabel extends JLabel {

        private Image logo;

        @Override
        public void paint(Graphics g) {
            logo = new ImageIcon(getClass().getResource("/RecursosMultimedia/pieFondo.jpg")).getImage();
            g.drawImage(logo, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelLogo;
    private javax.swing.JButton jButton_busca_cliente;
    private javax.swing.JButton jButton_busca_cliente2;
    private javax.swing.JButton jButton_busca_producto;
    private javax.swing.JButton jButton_calcular_cambio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelSerie;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner_Cantidad;
    public static javax.swing.JTable jTable_productos;
    private javax.swing.JLabel jlabelPie;
    private javax.swing.JTextField txtCodProducto;
    private javax.swing.JTextField txtCodProducto1;
    private javax.swing.JTextField txtResultadoCliente;
    private javax.swing.JTextField txtResultadoCliente1;
    private javax.swing.JTextField txtResultadoCliente2;
    private javax.swing.JTextField txt_cambio;
    private javax.swing.JTextField txt_cliente_buscar;
    private javax.swing.JTextField txt_descuento;
    private javax.swing.JTextField txt_efectivo;
    private javax.swing.JTextField txt_iva;
    private javax.swing.JTextField txt_subtotal;
    public static javax.swing.JTextField txt_total_pagar;
    // End of variables declaration//GEN-END:variables
}
