/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Validacion.Validacion;
import controlador.FacturaController;
import controlador.tda.lista.ListaEnlazada;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.Venta;
import vista.ModeloTablas.ModeloTablaVentas;

/**
 *
 * @author John
 */
public class Frm_Facturacion extends javax.swing.JDialog {

    private FacturaController fc = new FacturaController();
    private ModeloTablaVentas MTVentas = new ModeloTablaVentas();
    private Validacion validar = new Validacion();

    /**
     * Creates new form Frm_Facturacion
     */
    public Frm_Facturacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jTNombre.setEnabled(false);
        jTtelefono.setEnabled(false);
        jTDireccionCliente.setEnabled(false);
        jTEmail.setEnabled(false);
        jTableVentas.setEnabled(false);
        jBFacturar.setEnabled(false);
        jBProforma.setEnabled(false);
        cargarTableVentas(null);
    }

    public void limpiar() {
        jTCedula.setText(" ");
        jTNombre.setText(" ");
        jTDireccionCliente.setText(" ");
        jTEmail.setText(" ");
        jTtelefono.setText(" ");
    }

    public void DatosCliente() {
        String cedula = jTCedula.getText();
        Cliente cliente = new Cliente();
        jTNombre.setText(cliente.getRazonSocial());
        jTDireccionCliente.setText(cliente.getDireccion());
        jTEmail.setText(cliente.getIdentificacion());
        jTtelefono.setText(cliente.getTelefono());
        cargarTableVentas(cliente.getId_cliente());
    }

    public void cargarTableVentas(Integer id_cliente) {
        ListaEnlazada<Venta> listaVentas = new ListaEnlazada<Venta>();
        MTVentas.setLista(listaVentas);
        jTableVentas.setModel(MTVentas);
        jTableVentas.updateUI();
    }

    public void guardar() {
        if (jTNombre.getText().trim().isEmpty() || jTCedula.getText().trim().isEmpty() || jTDireccionCliente.getText().trim().isEmpty()
                || jTEmail.getText().trim().isEmpty() || jTtelefono.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campos vacios", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (validar.validarCedula(jTCedula.getText())) {
//                    if (proveedordao.getProveedores().getId_Proveedor() == null) {
//                        if (proveedordao.guardar()) {
//                            JOptionPane.showMessageDialog(null, "Registro Completo", "Ok", JOptionPane.INFORMATION_MESSAGE);
//                            limpiar();
//                            cargarTableVentas(fc.getVenta().get);
//                        } else {
//                            JOptionPane.showMessageDialog(null, "Error al registrar", "Error", JOptionPane.ERROR_MESSAGE);
//                        }
//                    }
                
            } else {
                JOptionPane.showMessageDialog(null, "Cedula no valida", "Error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVentas = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jBProforma = new javax.swing.JButton();
        jBFacturar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTtelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTEmail = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTCedula = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTDireccionCliente = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setText("FACTURAR");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(40, 10, 160, 40);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(30, 140, 730, 20);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(null);

        jTableVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVentasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableVentas);

        jPanel8.add(jScrollPane1);
        jScrollPane1.setBounds(10, 40, 690, 270);

        jLabel6.setText("Ventas Realizadas al Cliente");
        jPanel8.add(jLabel6);
        jLabel6.setBounds(10, 10, 170, 16);

        jBProforma.setText("Proformar");
        jBProforma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBProformaActionPerformed(evt);
            }
        });
        jPanel8.add(jBProforma);
        jBProforma.setBounds(610, 330, 90, 25);

        jBFacturar.setText("Facturar");
        jBFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFacturarActionPerformed(evt);
            }
        });
        jPanel8.add(jBFacturar);
        jBFacturar.setBounds(470, 330, 90, 25);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton1);
        jButton1.setBounds(340, 330, 90, 25);

        jPanel2.add(jPanel8);
        jPanel8.setBounds(20, 330, 730, 370);

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        jLabel5.setText("TELEFONO MOVIL:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(470, 180, 150, 30);
        jPanel2.add(jTtelefono);
        jTtelefono.setBounds(470, 210, 160, 22);

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        jLabel7.setText("EMAIL:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(470, 230, 100, 30);

        jTEmail.setToolTipText("");
        jPanel2.add(jTEmail);
        jTEmail.setBounds(470, 260, 260, 30);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(20, 310, 730, 20);

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        jLabel9.setText("DIRECCIÓN COMPRADOR:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(30, 200, 160, 30);

        jLabel10.setText("Busqueda del Cliente");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(30, 50, 190, 30);

        jLabel3.setText("Identificador:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 80, 140, 30);

        jTCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTCedulaKeyTyped(evt);
            }
        });
        jPanel2.add(jTCedula);
        jTCedula.setBounds(120, 80, 280, 30);

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btBuscar);
        btBuscar.setBounds(430, 80, 100, 30);

        jTDireccionCliente.setColumns(20);
        jTDireccionCliente.setRows(5);
        jScrollPane3.setViewportView(jTDireccionCliente);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(30, 230, 410, 70);

        jLabel2.setText("Nombre:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 170, 50, 16);

        jTNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNombreActionPerformed(evt);
            }
        });
        jPanel2.add(jTNombre);
        jTNombre.setBounds(120, 170, 280, 22);
        jPanel2.add(jSeparator3);
        jSeparator3.setBounds(30, 50, 730, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 780, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNombreActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        DatosCliente();
    }//GEN-LAST:event_btBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //        limpiar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFacturarActionPerformed
        //        guardar(true);
    }//GEN-LAST:event_jBFacturarActionPerformed

    private void jBProformaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBProformaActionPerformed

    }//GEN-LAST:event_jBProformaActionPerformed

    private void jTableVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVentasMouseClicked
        //        editarCarrito();
    }//GEN-LAST:event_jTableVentasMouseClicked

    private void jTCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTCedulaKeyTyped
        validar.validaSeaNumero(evt, jTCedula, 10);
    }//GEN-LAST:event_jTCedulaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Frm_Facturacion dialog = new Frm_Facturacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton jBFacturar;
    private javax.swing.JButton jBProforma;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTCedula;
    private javax.swing.JTextArea jTDireccionCliente;
    private javax.swing.JTextField jTEmail;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTable jTableVentas;
    private javax.swing.JTextField jTtelefono;
    // End of variables declaration//GEN-END:variables
}
