/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import controlador.dao.UsuarioContr;
import controlador.utiles.Utilidades;
import javax.swing.JOptionPane;
import vista.ModeloTablas.ModeloTablaUsuario;


/**
 *
 * @author Pc
 */
public class FrmCliente extends javax.swing.JFrame {

    /**
     * Creates new form FrmUsuario
     */
    private ModeloTablaUsuario mtu = new ModeloTablaUsuario();
    private UsuarioContr uc = new UsuarioContr();
    private Integer id;
    private Integer fila = -1;

    public FrmCliente() {
        initComponents();
        setLocationRelativeTo(null);
        //combo();
        //paneIden.setVisible(false);
    }

//    private void combo() {
//        this.cbxI.removeAllItems();
//
//        for (String aux : Utilidades.tiposI()) {
//            this.cbxI.addItem(aux);
//        }
////        cbxI.updateUI();
////        for (int i = 0; i < Utilidades.tiposI().length; i++) {
////            String[] aux = Utilidades.tiposI();
////            String[] a = new String[4];
////            a[0] = "SELECCIONAR";
////            for (int j = 0; j < a.length; j++) {
////                a[j + 1] = aux[j];
////                this.cbxI.addItem(a[j]);
////            }
////
////        }
//        cbxI.updateUI();
//
//        this.cbxR.removeAllItems();
//        for (String aux : Utilidades.tiposr()) {
//            this.cbxR.addItem(aux);
//        }
//        cbxR.updateUI();
//    }
//
//    public void cargarTabla() {
//        mtu.setLista(uc.listado());
//        tabla.setModel(mtu);
//        tabla.updateUI();
//    }
//
//    public void limpiar() {
//        uc.setUsuario(null);
//        txtNombre.setText("");
//        txtApellido.setText("");
//        txtCedula.setText("");
//        txtCorreo.setText("");
//        //txtvalor.setText("");
//    }
//
//    public void guardar() throws ExceptionInInitializerError {
//
//        uc.getUsuario().setId(id);
//        uc.getUsuario().setNombre(txtNombre.getText());
//        uc.getUsuario().setApelldo(txtApellido.getText());
//        uc.getUsuario().setTipoIndentificador(txtCedula.getText());
//        uc.getUsuario().setCorreo(txtCorreo.getText());
////            uc.getUsuario().setServicios(cbxservici.getSelectedItem().toString());
////            uc.getUsuario().setTipo(cbxtipo.getSelectedItem().toString());
////            uc.getUsuario().setDescripcion(txtdescrp.getText());
//        uc.guardar();
//        JOptionPane.showMessageDialog(null, "Se ha guardadao correctamente", "OK", JOptionPane.INFORMATION_MESSAGE);
//        cargarTabla();
//        limpiar();
//
//    }
//
//    private void modificar() {
//
//        uc.getUsuario().setId(id);
//        uc.getUsuario().setNombre(txtNombre.getText());
//        uc.getUsuario().setApelldo(txtApellido.getText());
//        uc.getUsuario().setTipoIndentificador(txtCedula.getText());
//        uc.getUsuario().setCorreo(txtCorreo.getText());
//        uc.modificar(fila);
//
//        JOptionPane.showMessageDialog(null, "Se ha modificado correctamente", "OK", JOptionPane.INFORMATION_MESSAGE);
//        cargarTabla();
//
//    }
//
//    private void seleccionar() {
//
//        fila = tabla.getSelectedRow();
//
//        if (fila >= 0) {
//            uc.setUsuario(uc.listado().obtenerDato(fila));
//            txtNombre.setText(uc.getUsuario().getNombre());
//            txtApellido.setText(uc.getUsuario().getApellido());
//            txtCedula.setText(uc.getUsuario().getTipoIndentificador());
//            txtCorreo.setText(uc.getUsuario().getCorreo());
////            cbxclasif.setSelectedItem(uc.getInmueble().getClasificacion());
////            cbxservici.setSelectedItem(uc.getInmueble().getServicios());
////            cbxtipo.setSelectedItem(uc.getInmueble().getTipo());
//        } else {
//
//            System.out.println("Selccionado");
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbxI = new javax.swing.JComboBox<>();
        txtCorreo = new javax.swing.JTextField();
        paneIden = new javax.swing.JPanel();
        txtCedula = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pasw = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbxR = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("NOMBRE");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, -1));
        jPanel3.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 270, -1));

        jLabel5.setText("APELLIDO");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 60, -1));

        jLabel4.setText("TIPO DE INDENTIFICACION");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 160, -1));

        cbxI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR" }));
        cbxI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbxIMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbxIMouseReleased(evt);
            }
        });
        cbxI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbxIKeyPressed(evt);
            }
        });
        jPanel3.add(cbxI, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, -1));
        jPanel3.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 270, -1));

        javax.swing.GroupLayout paneIdenLayout = new javax.swing.GroupLayout(paneIden);
        paneIden.setLayout(paneIdenLayout);
        paneIdenLayout.setHorizontalGroup(
            paneIdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneIdenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        paneIdenLayout.setVerticalGroup(
            paneIdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneIdenLayout.createSequentialGroup()
                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel3.add(paneIden, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 150, 30));

        jLabel8.setText("SEXO");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 60, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 170, -1));

        jLabel9.setText("CORREO");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 60, -1));
        jPanel3.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 270, -1));

        jLabel10.setText("CONTRA");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 60, -1));
        jPanel3.add(pasw, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 270, -1));

        jLabel7.setText("FECHA N");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 60, -1));
        jPanel3.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 270, -1));

        jLabel6.setText("TIPO DE ROL");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 100, -1));

        cbxR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(cbxR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 190, -1));

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 140, -1));

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 120, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 320, 470));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 160, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 320, 40));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 450));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 20, 470));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 460, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    //    guardar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbxIMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxIMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxIMouseReleased

    private void cbxIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbxIKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxIKeyPressed

    private void cbxIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxIMousePressed

        // TODO add your handling code here:
    }//GEN-LAST:event_cbxIMousePressed

    private void tablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMousePressed
      //  seleccionar();        // TODO add your handling code here:
    }//GEN-LAST:event_tablaMousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed


    }//GEN-LAST:event_jButton2ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxI;
    private javax.swing.JComboBox<String> cbxR;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JPanel paneIden;
    private javax.swing.JPasswordField pasw;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
